os: linux
dist: xenial
language: php

jobs:
  include:
    - php: 7.0
      env: USE_PHIVE=false
    - php: 7.1
      env: USE_PHIVE=false
    - php: 7.2
      env: USE_PHIVE=true
    - php: 7.3
      env: USE_PHIVE=true
    - php: 7.4
      env: USE_PHIVE=true

notifications:
    on_success: never
    on_failure: always

cache:
 directories:
    - "$HOME/.phive"
    - "$HOME/.phive/phars"
    - "$HOME/.cache/composer"
    - "$HOME/.composer/cache"
    - "$HOME/.gnupg"

before_install:
  - if $USE_PHIVE; then
    wget -O phive.phar "https://phar.io/releases/phive.phar" &&
    gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79 &&
    gpg --verify phive.phar.asc phive.phar &&
    rm phive.phar.asc &&
    chmod +x phive.phar &&
    mkdir -p "$HOME/bin" &&
    export PATH="$HOME/bin:$PATH" &&
    mv phive.phar $HOME/bin/phive;
    fi

install:
  - composer install
  - if $USE_PHIVE; then phive --no-progress install --trust-gpg-keys CF1A108D0E7AE720,31C7E470E2138192; fi

script:
  - tools/phpcs
  - tools/phpstan analyse src --level max
  - vendor/bin/phpunit --testsuite alltest
