os: linux
dist: xenial
language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

notifications:
    on_success: never
    on_failure: always

cache:
 directories:
   - $HOME/.composer/cache/files

before_install:
  - wget -O phive.phar "https://phar.io/releases/phive.phar"
  - wget -O phive.phar.asc "https://phar.io/releases/phive.phar.asc"
  - gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79
  - gpg --verify phive.phar.asc phive.phar
  - rm phive.phar.asc
  - chmod +x phive.phar
  - mv phive.phar /usr/local/bin/phive

install:
  - composer install
  - phive install

script:
  - tools/phpcs
  - tools/phpstan
  - vendor/bin/phpunit --testsuite alltest
