os: linux
dist: bionic
language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

notifications:
    on_success: never
    on_failure: always

cache:
 directories:
   - $HOME/.composer/cache/files

script:
  - phpunit --testsuite alltest
